DELETE FROM FILMS LIMIT 100;
DELETE FROM USERS LIMIT 100;
DELETE FROM FILMS_GENRE LIMIT 100;
DELETE FROM GENRE LIMIT 100;
DELETE FROM RATE LIMIT 100;
DELETE FROM FRIENDS LIMIT 100;
DELETE FROM FRIENDSHIP_STATUS LIMIT 100;


INSERT INTO PUBLIC.GENRE (GENRE_ID, NAME)
VALUES (1, 'Комедия'),
       (2, 'Драма'),
       (3, 'Мультфильм'),
       (4, 'Триллер'),
       (5, 'Документальный'),
       (6, 'Боевик');

INSERT INTO PUBLIC.RATE (RATE_ID, NAME)
VALUES (1, 'G'),
       (2, 'PG'),
       (3, 'PG_13'),
       (4, 'R'),
       (5, 'NC_17');

INSERT INTO PUBLIC.FRIENDSHIP_STATUS (STATUS_ID, NAME)
VALUES (1, 'CONFIRMED'),
       (2, 'UNCONFIRMED');
